debug: 1

device: /dev/ttyAMA4
frame_id: gps
rate: 4
nav_rate: 4
dynamic_model: airborne2
fix_mode: auto

uart1:
  baudrate: 38400

inf:
  all: true

publish:
  nav:
    status: true
    posllh: true
    velned: true
    sol: true