device: /dev/ttyAMA4
uart1:
  baudrate: 57600

debug: 1
frame_id: gps
rate: 4
nav_rate: 4
dynamic_model: portable
#fix_mode: auto

gnss:
  sbas: true
sbas:
  max: 3
  usage: 3 # ranging source + corrections

publish:
  nav:
    pvt: true
