debug: 1

device: /dev/ttyAMA4
frame_id: gps
rate: 4
nav_rate: 4
dynamic_model: portable
fix_mode: auto
gnss:
  sbas: true
sbas:
  max: 3
  usage: 3 # ranging source + corrections

uart1:
  baudrate: 38400

inf:
  all: true

publish:
  nav:
    status: true
    posllh: true
    velned: true
    sol: true