debug: 1

device: /dev/ttyAMA4
frame_id: gps_module
rate: 5
nav_rate: 5
dynamic_model: airborne2
fix_mode: 3
enable_ppp: true
dr_limit: 1

inf:
  all: true

publish:
  all: true
  esf: false
  aid:
    hui: false
  nav:
    posecef: false